apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-03-06T15:14:41Z"
  creationTimestamp: "2025-03-06T15:14:36Z"
  name: pprof-example-service
  namespace: default
  resourceVersion: "210618"
  uid: 41f24e12-cf52-4e75-b115-d706e1bcf5bb
subsets:
- addresses:
  - ip: 10.42.0.37
    nodeName: k3d-test-cluster-server-0
    targetRef:
      kind: Pod
      name: pprof-example-deployment-55c897bb65-skbz4
      namespace: default
      uid: e2a3a30a-ee5b-42a8-8c18-ef6f8cab0130
  - ip: 10.42.0.38
    nodeName: k3d-test-cluster-server-0
    targetRef:
      kind: Pod
      name: pprof-example-deployment-55c897bb65-8n5js
      namespace: default
      uid: c47524e9-9144-48a4-9971-68aec74108c9
  - ip: 10.42.0.39
    nodeName: k3d-test-cluster-server-0
    targetRef:
      kind: Pod
      name: pprof-example-deployment-55c897bb65-hdmhw
      namespace: default
      uid: 1b02ea63-a14d-49a1-8c26-d165f0a94180
  ports:
  - port: 6060
    protocol: TCP
