apiVersion: apps/v1
kind: Deployment
metadata:
  name: pprof-example-deployment
  labels:
    app: pprof
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pprof
  template:
    metadata:
      labels:
        app: pprof
    spec:
      containers:
      - name: pprof-example
        image: ghcr.io/alexandrelamarre/pprof-chaos-tool:v0.1.0-pre-alpha.2
        ports:
        - containerPort: 6060
---

apiVersion: v1
kind: Service
metadata:
  name: pprof-example-service
  labels:
    app: pprof
spec:
  selector:
    app: pprof
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6060
  type: ClusterIP

apiVersion: resources.cattle.io/v1alpha1
kind : PprofMonitor
metadata:
  name: pprofmonitor-sample
  namespace: default
spec:
  selector:
    matchLabels:
      app: pprof
  namespaceSelector:
    any : true
  endpoint:
    targetPort : 80
  config:
    profile:
      seconds : 120
    heap:
      seconds : 120